name = "face-score-pages"
main = ""
compatibility_date = "2024-01-01"

[site]
bucket = "./public"
entry-point = "./functions"

[vars]
WECHAT_APPID = "${WECHAT_APPID}"
WECHAT_PRIVATE_KEY = "${WECHAT_PRIVATE_KEY}"

[env.production]
name = "face-score-pages"
