name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Pages (with Functions)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 🐾
        uses: actions/checkout@v3

      - name: Deploy Pages 🔥
        uses: cloudflare/pages-action@v1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          projectName: "face-score-pages" 
          directory: "public"            
          branch: main
          env: |
            ${{ if secrets.PROMPT_SCORE }}PROMPT_SCORE=${{ secrets.PROMPT_SCORE }}${{ endif }}
            ${{ if secrets.PROMPT_TEMPERAMENT }}PROMPT_TEMPERAMENT=${{ secrets.PROMPT_TEMPERAMENT }}${{ endif }}
            ${{ if secrets.AI_MODEL_ID }}AI_MODEL_ID=${{ secrets.AI_MODEL_ID }}${{ endif }}
            ${{ if secrets.FACEPP_KEY }}FACEPP_KEY=${{ secrets.FACEPP_KEY }}${{ endif }}
            ${{ if secrets.FACEPP_SECRET }}FACEPP_SECRET=${{ secrets.FACEPP_SECRET }}${{ endif }}
            ${{ if secrets.TURNSTILE_SECRET_KEY }}TURNSTILE_SECRET_KEY=${{ secrets.TURNSTILE_SECRET_KEY }}${{ endif }}
            ${{ if secrets.TURNSTILE_SITE_KEY }}TURNSTILE_SITE_KEY=${{ secrets.TURNSTILE_SITE_KEY }}${{ endif }}
            ${{ if secrets.ADMIN_USERNAME }}ADMIN_USERNAME=${{ secrets.ADMIN_USERNAME }}${{ endif }}
            ${{ if secrets.ADMIN_PASSWORD }}ADMIN_PASSWORD=${{ secrets.ADMIN_PASSWORD }}${{ endif }}
            ${{ if secrets.GITHUB_CLIENT_ID }}GITHUB_CLIENT_ID=${{ secrets.GITHUB_CLIENT_ID }}${{ endif }}
            ${{ if secrets.GITHUB_CLIENT_SECRET }}GITHUB_CLIENT_SECRET=${{ secrets.GITHUB_CLIENT_SECRET }}${{ endif }}
            ${{ if secrets.GITHUB_ALLOWED_USERS }}GITHUB_ALLOWED_USERS=${{ secrets.GITHUB_ALLOWED_USERS }}${{ endif }}
