name: Deploy to Cloudflare

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    name: Deploy Pages (with Functions)
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 🐾
        uses: actions/checkout@v4

      - name: Deploy Pages 🚀
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.ACCOUNT_ID }}
          command: pages deploy public --project-name=face-score-pages
          secrets: |
            WECHAT_APP_ID
            WECHAT_APP_SECRET
        env:
          WECHAT_APP_ID: ${{ secrets.WECHAT_APP_ID }}
          WECHAT_APP_SECRET: ${{ secrets.WECHAT_APP_SECRET }}